apiVersion: v1
kind: ConfigMap
metadata:
  name: webgitcoder-config
  namespace: webgitcoder
  labels:
    app: webgitcoder
data:
  # Configuraciones de la aplicación (si las necesitas)
  APP_NAME: "WebGitCoder"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
